development:
  adapter: postgresql
  encoding: utf8
  database: sdl_admin_dashboard_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: sdl_admin_dashboard_test
  pool: 5
  username: judywu
  password:

staging:
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: <%= (ENV['APP_DB_DATABASE'] || Rails.application.secrets.APP_DB_DATABASE) %>
  username: <%= (ENV['APP_DB_USERNAME'] || Rails.application.secrets.APP_DB_USERNAME) %>
  password: <%= (ENV['APP_DB_PASSWORD'] || Rails.application.secrets.APP_DB_PASSWORD) %>

production:
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: <%= (ENV['APP_DB_DATABASE'] || Rails.application.secrets.APP_DB_DATABASE) %>
  username: <%= (ENV['APP_DB_USERNAME'] || Rails.application.secrets.APP_DB_USERNAME) %>
  password: <%= (ENV['APP_DB_PASSWORD'] || Rails.application.secrets.APP_DB_PASSWORD) %>
  # host: omh-postgres
  host: <%= (ENV['APP_DB_HOST'] || Rails.application.secrets.APP_DB_HOST) %>

  # port: 5432

