development:
  adapter: postgresql
  encoding: utf8
  database: sdl_admin_dashboard_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: sdl_admin_dashboard_test
  pool: 5
  username: judywu
  password:

staging:
  adapter: postgresql
  encoding: utf8
  database: <%= (ENV['db_name'] || Rails.application.secrets.db_name) %>
  pool: 5
  username: <%= (ENV["db_user"] || Rails.application.secrets.db_user) %>
  password: <%= (ENV["db_password"] || Rails.application.secrets.db_password) %>

production:
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: <%= ENV['db_name'] || Rails.application.secrets.db_name %>
  username: <%= ENV['db_user'] || Rails.application.secrets.db_user%>
  password: <%= ENV['db_password'] || Rails.application.secrets.db_password%>
  # host: omh-postgres
  # port: 5432

