development: 
  adapter: postgresql
  encoding: utf8
  database: sdl_admin_dashboard_development 
  pool: 5
  username: 
  password: 

test: 
  adapter: postgresql
  encoding: utf8
  database: sdl_admin_dashboard_test
  pool: 5
  username: judywu
  password: 

production: 
  adapter: postgresql
  encoding: utf8
  database: <%= Rails.application.secrets.db_name %>
  pool: 5
  username: <%= Rails.application.secrets.db_user %>
  password: <%= Rails.application.secrets.db_password %>

