development: 
  adapter: postgresql
  encoding: utf8
  database: sdl_admin_dashboard_development 
  pool: 5
  username: 
  password: 

test: 
  adapter: postgresql
  encoding: utf8
  database: sdl_admin_dashboard_test
  pool: 5
  username: judywu
  password: 

staging: 
  adapter: postgresql
  encoding: utf8
  database: <%= Rails.application.secrets.db_name %>
  pool: 5
  username: <%= Rails.application.secrets.db_user %>
  password: <%= Rails.application.secrets.db_password %>

production: 
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: <%= ENV['APP_DB_DATABASE'] || Rails.application.secrets.db_name %>
  username: <%= ENV['APP_DB_USERNAME'] || Rails.application.secrets.db_user%>
  password: <%= ENV['APP_DB_PASSWORD'] || Rails.application.secrets.db_password%>
  host: omh-postgres
  port: 5432

