# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae0758a1d349f30e6fb21fee0b0b8a96c2981f200476ead301b3d75f01305146b2e60a42de62cd363da897e3b21177988076b1d6807d935260f974be974da2f3

test:
  secret_key_base: b3072e5e61e516875396c8690d5ca01d9163dab9b95d25bbce5d68501ffdf0b422556bb9a3ae4a562c67dc21c50925466716d9b3a44265de61d6c1e3dc678923

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  db_name: admindashboard
  db_user: postgres
  db_password: s8asd90s

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  db_name: admindashboard
  db_user: postgres
  db_password: 

